main:
    random_seed: 0
    saved_dir: './models/lits_seg/adapt_from_scratch_norm_trainable_only/train'

dataset:
    name: 'LitsAdaptDataset'
    kwargs:
        data_split_file_path: '../lits/data_split/adaptation.csv'
        preprocess:
            - name: 'Resample'
              kwargs:
                  output_spacing: [2.5, 2.5, 5]
            - name: 'Clip'
              kwargs:
                  mins: -1000
                  maxs: 1000
            - name: 'MinMaxScale'
            - name: 'RandomCrop'
              kwargs:
                  size: [96, 96, 16]
        transforms:
            - name: 'NonLinearTransform'
              kwargs:
                  prob: 0.9
            - name: 'LocalPixelShuffling'
              kwargs:
                  prob: 0.5
            - name: 'Painting'
              kwargs:
                  prob: 0.9
                  inpaint_rate: 0.2

dataloader:
    name: 'Dataloader'
    kwargs:
        train:
            batch_size: 8
            drop_last: true
        valid:
            batch_size: 1
            drop_last: false
        grad_accumulation_steps: 2
        shuffle: true
        num_workers: 8

net:
    name: 'ModelsGenesisSegNet'
    kwargs:
        in_channels: 1
        out_channels: 1
        norm_trainable_only: true

losses:
    - name: 'MSELoss'
      alias: 'mse_loss'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.001

logger:
    name: 'LitsAdaptLogger'

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'loss'
        saved_freq: 1000
        valid_freq: 10001

trainer:
    name: 'LitsAdaptTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 10000
