main:
    random_seed: 0
    saved_dir: './models/vipcup_seg/network_alchemy_pre_trained_mr_fine_tuned/maximization/data_split_0/train'

dataset:
    name: 'VipcupSegDataset'
    kwargs:
        data_split_file_path: '../vipcup_resampled/data_split/0.csv'
        transforms:
            - name: 'Clip'
              kwargs:
                  mins: -1000
                  maxs: 1000
            - name: 'MinMaxScale'
        augments:
            - name: 'RandomCrop'
              kwargs:
                  size: [96, 96, 16]

dataloader:
    name: 'Dataloader'
    kwargs:
        train:
            batch_size: 16
            drop_last: true
        valid:
            batch_size: 1
            drop_last: false
        shuffle: true
        num_workers: 8

net:
    name: 'ModelsGenesisSegNet'
    kwargs:
        in_channels: 1
        out_channels: 2
        weight_path: './models/vipcup_seg/network_alchemy_pre_trained_mr_fine_tuned/modification/data_split_0/train/checkpoints/model_250.pth'
losses:
    - name: 'CrossEntropyLossWrapper'
      alias: 'cross_entropy_loss'
      weight: 0.5
    - name: 'DiceLoss'
      alias: 'dice_loss'
      weight: 0.5
      kwargs:
          numerator_smooth: 0
          denominator_smooth: 0.0000001
    - name: 'BatchNormGammaLoss'
      alias: 'bn_gamma_loss'
      weight: 0.00001

metrics:
    - name: 'Dice'
      alias: 'dice'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.0005

logger:
    name: 'VipcupSegLogger'

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'max'
        target: 'Dice'
        saved_freq: 50
        valid_freq: 10

trainer:
    name: 'VipcupSegTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 1500
        half_bn_grad: true