main:
    random_seed: 0
    saved_dir: './models/acdc_seg/adapt_pre_trained_without_decoder_ct/train'

dataset:
    name: 'AcdcAdaptDataset'
    kwargs:
        data_split_file_path: '../acdc/data_split/0.csv'
        preprocess:
            - name: 'Resample'
              kwargs:
                  output_spacing: [2, 2, 2]
            - name: 'Clip'
              kwargs:
                  mins: 0
                  maxs: 4000
            - name: 'MinMaxScale'
            - name: 'RandomCrop'
              kwargs:
                  size: [96, 96, 16]
        transforms:
            - name: 'NonLinearTransform'
              kwargs:
                  prob: 0.9
            - name: 'LocalPixelShuffling'
              kwargs:
                  prob: 0.5
            - name: 'Painting'
              kwargs:
                  prob: 0.9
                  inpaint_rate: 0.2

dataloader:
    name: 'Dataloader'
    kwargs:
        train:
            batch_size: 8
            drop_last: true
        valid:
            batch_size: 1
            drop_last: false
        grad_accumulation_steps: 2
        shuffle: true
        num_workers: 8

net:
    name: 'ModelsGenesisSegNet'
    kwargs:
        in_channels: 1
        out_channels: 1
        weight_path: './weights/models_genesis.pth'
        loaded_modules: ['encoder']

losses:
    - name: 'MSELoss'
      alias: 'mse_loss'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.001

logger:
    name: 'AcdcAdaptLogger'

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'loss'
        saved_freq: 1000
        valid_freq: 10001

trainer:
    name: 'AcdcAdaptTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 10000
