main:
    random_seed: 0
    saved_dir: './models/vipcup_seg/network_alchemy_pre_trained_mr_fine_tuned/identification/data_split_1/train'

dataset:
    name: 'VipcupSegDataset'
    kwargs:
        data_split_file_path: '../vipcup_resampled/data_split/1.csv'
        transforms:
            - name: 'Clip'
              kwargs:
                  mins: -1000
                  maxs: 1000
            - name: 'MinMaxScale'
        augments:
            - name: 'RandomCrop'
              kwargs:
                  size: [96, 96, 16]

dataloader:
    name: 'Dataloader'
    kwargs:
        train:
            batch_size: 16
            drop_last: true
        valid:
            batch_size: 1
            drop_last: false
        shuffle: true
        num_workers: 8

net:
    name: 'ModelsGenesisSegNet'
    kwargs:
        in_channels: 1
        out_channels: 2
        weight_path: './weights/ours_mr.pth'
        norm_trainable_only: true

losses:
    - name: 'CrossEntropyLossWrapper'
      alias: 'cross_entropy_loss'
    - name: 'DiceLoss'
      alias: 'dice_loss'
      kwargs:
          numerator_smooth: 0
          denominator_smooth: 0.0000001

metrics:
    - name: 'Dice'
      alias: 'dice'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.0005

logger:
    name: 'VipcupSegLogger'

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'max'
        target: 'Dice'
        saved_freq: 150
        valid_freq: 10

trainer:
    name: 'VipcupSegTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 750
