main:
    random_seed: 0
    saved_dir: './models/lits_seg/from_scratch_fine_tuned/data_split_2/train'

dataset:
    name: 'LitsSegDataset'
    kwargs:
        data_split_file_path: '../lits/data_split/2.csv'
        transforms:
            - name: 'Resample'
              kwargs:
                  output_spacing: [2.5, 2.5, 5]
            - name: 'Clip'
              kwargs:
                  mins: -1000
                  maxs: 1000
            - name: 'MinMaxScale'
        augments:
            - name: 'RandomCrop'
              kwargs:
                  size: [96, 96, 16]

dataloader:
    name: 'Dataloader'
    kwargs:
        train:
            batch_size: 8
            drop_last: true
        valid:
            batch_size: 1
            drop_last: false
        grad_accumulation_steps: 2
        shuffle: true
        num_workers: 8

net:
    name: 'ModelsGenesisSegNet'
    kwargs:
        in_channels: 1
        out_channels: 3

losses:
    - name: 'CrossEntropyLossWrapper'
      alias: 'cross_entropy_loss'
    - name: 'DiceLoss'
      alias: 'dice_loss'
      kwargs:
          numerator_smooth: 0
          denominator_smooth: 0.0000001

metrics:
    - name: 'Dice'
      alias: 'dice'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.001

logger:
    name: 'LitsSegLogger'

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'max'
        target: 'DiceLiver'
        saved_freq: 500
        valid_freq: 10

trainer:
    name: 'LitsSegTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 5000
